# O Método Fácil {#o-metodo-facil}


O objetivo desse livro é te direcionar a um novo estado da mente. Em contraste com método tradicional de parar — que você começa com um sentimento de estar subindo o Monte Everest e passa as próximas semanas com desejos e se sentindo privado —, você já começa com um sentimento de euforia, como se tivesse se curado de uma doença terrível. A partir disso, quanto mais você avança na vida, mais você vai olhar para esse período de tempo e se perguntar por que você usou qualquer pornô em primeiro lugar. Você olhará para outros usuários com um sentimento de pena, ao invés de inveja.

Se você não é alguém que nunca foi viciado (lendo para alguém significante) ou tenha parado (ou está nos dias de jejum de uma "dieta pornô") é essencial que você continue usando até que você termine o livro completamente. Isso pode soar contraditório, e essa instrução para continuar se masturbando com pornografia causa mais objeções que qualquer outra, mas enquanto você continuar lendo seu desejo de usar pornografia vai diminuir gradualmente. **Leve a sério essa instrução: Tentar abandonar o vício cedo não irá lhe beneficiar.**

Muitos não terminam o livro porque sentem que têm que desistir de algo, alguns até leem uma linha por dia para procrastinar o evento maligno. Veja da seguinte forma: o que você tem a perder? Se você não parar ao final do livro, você não está pior do que está agora. Isso é, por definilçao, uma Aposta de Pascal, uma aposta feita quando você não tem nada a perder e muitas chances de grandes ganhos.

A propósito, se você não assiste pornô há alguns dias ou semanas, mas não tem certeza se você é um usuário, ex-usuário ou um não-usuário, então não use pornô para se masturbar enquanto você lê. Na verdade, você já é um não-usuário, mas temos que deixar seu cérebro se entender com seu corpo. Ao final do livro, você será um não-usuário feliz. O Método Fácil é completamente contrário ao método normal, onde se lista as consideráveis desvantagens da pornografia e diz:
*"Se eu ficar tempo longo suficiente sem pornô, eventualmente o desejo vai desaparecer e eu posso desfrutar da vida de novo, livre da escravidão."*
Esse é o modo lógico, com milhares parando todo dia usando esse método. Contudo, é difícil ter sucesso pelas seguintes razões:

**Parar com PMO não é o problema real.** Toda vez que você termina uma sessão, você parou de usar. Você pode ter fortes razões no primeiro dia da sua dieta pornô de "uma a cada quatro dias" para dizer *"Não quero usar pornô nem me masturbar mais."* Todos usuários fazem isso e as razões deles são mais poderosas que você pode imaginar. O real problema é o dia dois, dez, ou dez mil, quando num momento de fraqueza você pensa "só uma olhadinha", vai querer outra e de repente você está viciado de novo.

**A consciência dos riscos à saúde gera mais medo, tornando mais difícil parar.** Diga a um usuário que isso está destruindo sua virilidade e a primeira coisa que ele irá fazer é procurar algo para levantar a dopamina: um cigarro, álcool ou até abrir o navegador e procurar pornografia.

**Todas as razões para parar na verdade dificultam.** Isso é por duas razões. Primeiro, estamos continuamente sendo forçados a abandonar nosso "pequeno amigo" ou alguma muleta, vício ou prazer (seja de qual maneira que o usuário perceba). Segundo, elas criam uma "cortina". Nós não nos masturbamos pelas razões que devemos parar. A verdadeira questão é: por que queremos ou precisamos fazer isso?

Com o Método Fácil, nós (inicialmente) nos esquecemos das razões pela qual gostaríamos de parar, encaramos o problema da pornografia e perguntamos a nós mesmos as seguintes questões:

1.  O que a pornografia está fazendo por mim?

2.  Eu realmente estou gostando disso?

3.  Eu realmente preciso viver sabotando minha mente e meu corpo?

A bela verdade é que *toda pornografia* não faz absolutamente nada por você. Deixe-me deixar muito claro: não é que as desvantagens de ser um usuário pesam mais que as vantagens, é que há ***zero*** vantagens em ver pornografia.

A maioria dos usuários acham necessário racionalizar os porquês de usarem pornô, mas as razões que eles encontram são falácias e ilusões.

Primeiramente, nós vamos remover essas falácias e ilusões. Na verdade, você logo irá notar que não tem nada para desistir. Não só isso, mas há ganhos positivos e maravilhosos em não ser mais um usuário de PMO, sendo o bem-estar e felicidade apenas dois desses ganhos. Uma vez que as ilusões de que a vida nunca será tão agradável sem pornografia é removida — perceber que não só a vida é igualmente agradável sem isso, mas infinitamente melhor — e uma vez que os sentimentos de estar sendo privado ou de se estar perdendo algo são erradicados, nós voltaremos a reconsiderar o aumento de bem estar e felicidade — e as outras milhares de razões para abandonar a pornografia. Essas percepções se tornarão ajudas positivas adicionais para te ajudar a alcançar o que você realmente deseja: desfrutar sua vida livre da escravidão do vício em pornografia!
